on: [push, pull_request]

name: Code Analysis
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Cucumber
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
      - run: npm install
      - run: npm test
